# Generated by Django 6.0.3 on 2026-03-09 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('telephone_contact', models.CharField(max_length=20)),
                ('adresse_livraison', models.TextField()),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('EN_COURS', 'En cours de livraison'), ('LIVREE', 'Livrée')], default='ATTENTE', max_length=20)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_passees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('FRUITS', 'Fruits'), ('LEGUMES', 'Légumes'), ('CEREALES', 'Céréales'), ('TUBERCULES', 'Tubercules')], default='LEGUMES', max_length=20)),
                ('prix', models.PositiveIntegerField()),
                ('unite', models.CharField(default='kg', help_text='ex: kg, sac, filet', max_length=20)),
                ('quantite_stock', models.PositiveIntegerField(default=0)),
                ('zone_production', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='produits/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mes_produits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='marche.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marche.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('CLIENT', 'Client / Consommateur'), ('AGRI', 'Agriculteur / Producteur')], default='CLIENT', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(default='Conakry', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
