# Generated by Django 6.0.3 on 2026-03-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marche', '0002_rename_date_ajout_produit_date_publication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée'), ('EN_COURS', 'En cours de livraison'), ('LIVREE', 'Livrée')], default='ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
